import type { TextBlock } from '@contracts/document'
import { TextImage } from './TextImage'

export function BlockEditor({ block, update }: { block: TextBlock; update: (block: TextBlock) => void }) {
  if (block.type === 'image') return <><TextImage block={block} /><label>Описание картинки<input value={block.alt} maxLength={500} onChange={e => update({ ...block, alt: e.target.value })} /></label><label>Ширина · {block.width}%<input type="range" min={10} max={100} value={block.width} onChange={e => update({ ...block, width: Number(e.target.value) })} /></label><label>Положение<select value={block.align} onChange={e => update({ ...block, align: e.target.value as typeof block.align })}><option value="left">Слева</option><option value="center">По центру</option><option value="right">Справа</option></select></label></>
  if (block.type === 'pageBreak') return <div className="page-break-label">Следующая страница</div>
  if (block.type === 'heading') return <div className="heading-edit"><select aria-label="Уровень заголовка" value={block.level} onChange={(event) => update({ ...block, level: Number(event.target.value) as 1 | 2 | 3 })}><option value={1}>Заголовок 1</option><option value={2}>Заголовок 2</option><option value={3}>Заголовок 3</option></select><input aria-label="Текст заголовка" maxLength={300} className={`heading-level-${block.level}`} value={block.text} placeholder="Заголовок раздела" onChange={(event) => update({ ...block, text: event.target.value })} /></div>
  if (block.type === 'paragraph') return <textarea className="paragraph-edit" aria-label="Текст абзаца" maxLength={12000} rows={Math.min(15, Math.max(3, Math.ceil(block.text.length / 65)))} value={block.text} placeholder="Начните писать здесь…" onChange={(event) => update({ ...block, text: event.target.value })} />
  if (block.type === 'list') return <div className="list-edit"><label className="checkbox-label"><input type="checkbox" checked={block.ordered} onChange={(event) => update({ ...block, ordered: event.target.checked })} />Нумерованный список</label>
    {block.items.map((item, index) => <div className="list-item-edit" key={index}><span>{block.ordered ? `${index + 1}.` : '•'}</span><textarea aria-label={`Пункт ${index + 1}`} maxLength={2000} rows={2} value={item} onChange={(event) => update({ ...block, items: block.items.map((value, at) => at === index ? event.target.value : value) })} /><button className="icon-button" aria-label={`Удалить пункт ${index + 1}`} disabled={block.items.length === 1} onClick={() => update({ ...block, items: block.items.filter((_, at) => at !== index) })}>×</button></div>)}
    <button className="text-button" disabled={block.items.length >= 50} onClick={() => update({ ...block, items: [...block.items, ''] })}>＋ Пункт списка</button></div>
  return <div className="table-edit"><div className="table-scroll"><table><thead><tr>{block.columns.map((column, index) => <th key={index}><input aria-label={`Название колонки ${index + 1}`} maxLength={120} value={column} onChange={(event) => update({ ...block, columns: block.columns.map((value, at) => at === index ? event.target.value : value) })} /></th>)}</tr></thead><tbody>{block.rows.map((row, index) => <tr key={index}>{row.map((cell, col) => <td key={col}><textarea rows={2} maxLength={1200} aria-label={`Строка ${index + 1}, колонка ${col + 1}`} value={cell} onChange={(event) => update({ ...block, rows: block.rows.map((value, at) => at === index ? value.map((text, j) => j === col ? event.target.value : text) : value) })} /></td>)}</tr>)}</tbody></table></div>
    <div className="table-buttons"><button disabled={block.rows.length >= 100} onClick={() => update({ ...block, rows: [...block.rows, block.columns.map(() => '')] })}>＋ Строка</button><button disabled={block.rows.length === 0} onClick={() => update({ ...block, rows: block.rows.slice(0, -1) })}>− Строка</button><button disabled={block.columns.length >= 6} onClick={() => update({ ...block, columns: [...block.columns, 'Колонка'], rows: block.rows.map((row) => [...row, '']) })}>＋ Колонка</button><button disabled={block.columns.length === 1} onClick={() => update({ ...block, columns: block.columns.slice(0, -1), rows: block.rows.map((row) => row.slice(0, -1)) })}>− Колонка</button></div></div>
}
