import { useMemo, useState } from 'react'
import { blankCell, blankWorksheet, type SpreadsheetContent, type Cell, type Worksheet } from '@contracts/office'
import { calculateWorksheet, columnLabel } from '@contracts/formulas'
import { NumberCellInput } from './NumberCellInput'

export function SpreadsheetEditor({ content, update, preview }: { content: SpreadsheetContent; update: (content: SpreadsheetContent) => void; preview: boolean }) {
  const [selected, setSelected] = useState(content.worksheets[0]!.id)
  const [address, setAddress] = useState<[number, number]>([0, 0])
  const sheet = content.worksheets.find(item => item.id === selected) ?? content.worksheets[0]!
  const r = Math.min(address[0], sheet.rows.length - 1), c = Math.min(address[1], sheet.columns.length - 1)
  const cell = sheet.rows[r]!.cells[c]!
  const results = useMemo(() => calculateWorksheet(sheet), [sheet])
  const change = (next: Worksheet) => update({ ...content, worksheets: content.worksheets.map(item => item.id === sheet.id ? next : item) })
  const changeCell = (next: Cell, row = r, column = c) => change({ ...sheet, rows: sheet.rows.map((item, i) => i === row ? { ...item, cells: item.cells.map((value, j) => j === column ? next : value) } : item) })
  function typeChanged(type: Cell['type']) {
    const common = { id: cell.id, format: cell.format, bold: cell.bold }
    const next: Cell = type === 'number' ? { ...common, type, value: Number.isFinite(Number(cell.value)) ? Number(cell.value) : 0 } : type === 'boolean' ? { ...common, type, value: cell.value === true } : type === 'date' ? { ...common, type, value: new Date().toISOString().slice(0, 10) } : { ...common, type, value: type === 'formula' ? '=SUM(A1:A2)' : String(cell.value) }
    changeCell(next)
  }
  function addSheet() { let number = 1; while (content.worksheets.some(item => item.name.toLowerCase() === `лист ${number}`)) number++; const next = blankWorksheet(`Лист ${number}`); update({ ...content, worksheets: [...content.worksheets, next] }); setSelected(next.id); setAddress([0, 0]) }
  function display(input: Cell, row: number, col: number) {
    const value = results[row]![col]!
    if (typeof value === 'boolean') return value ? 'ИСТИНА' : 'ЛОЖЬ'
    if (typeof value !== 'number' || input.format === 'general') return String(value)
    return new Intl.NumberFormat('ru-RU', input.format === 'percent' ? { style: 'percent', maximumFractionDigits: 1 } : input.format === 'currency' ? { style: 'currency', currency: 'RUB' } : { minimumFractionDigits: input.format === 'integer' ? 0 : 2, maximumFractionDigits: input.format === 'integer' ? 0 : 2 }).format(value)
  }
  return <div className="spreadsheet-editor"><nav className="office-tabs" aria-label="Листы">{content.worksheets.map(item => <button className={item.id === sheet.id ? 'selected' : ''} key={item.id} onClick={() => { setSelected(item.id); setAddress([0, 0]) }}>{item.name || 'Лист'}</button>)}{!preview && <button disabled={content.worksheets.length >= 5} onClick={addSheet}>＋ Лист</button>}</nav>
    {!preview && <><div className="office-toolbar"><label>Название листа<input value={sheet.name} maxLength={31} onChange={e => change({ ...sheet, name: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={sheet.headerRow} onChange={e => change({ ...sheet, headerRow: e.target.checked })} />Первая строка — заголовок</label><button disabled={content.worksheets.length === 1} onClick={() => { if (window.confirm('Удалить лист и его содержимое?')) update({ ...content, worksheets: content.worksheets.filter(item => item.id !== sheet.id) }) }}>Удалить лист</button></div>
      <div className="cell-properties"><strong>{columnLabel(c)}{r + 1}</strong><label>Тип<select value={cell.type} onChange={e => typeChanged(e.target.value as Cell['type'])}><option value="text">Текст</option><option value="number">Число</option><option value="formula">Формула</option><option value="date">Дата</option><option value="boolean">Логическое</option></select></label><label>Формат<select value={cell.format} onChange={e => changeCell({ ...cell, format: e.target.value as Cell['format'] })}><option value="general">Общий</option><option value="number">Два знака</option><option value="integer">Целое</option><option value="percent">Процент</option><option value="currency">Рубли</option></select></label><label className="checkbox-label"><input type="checkbox" checked={cell.bold} onChange={e => changeCell({ ...cell, bold: e.target.checked })} />Жирный</label><label>Ширина колонки<input type="number" min={8} max={60} value={sheet.columns[c]!.width} onChange={e => { const width = Number(e.target.value); if (width >= 8 && width <= 60) change({ ...sheet, columns: sheet.columns.map((item, i) => i === c ? { ...item, width } : item) }) }} /></label></div>
      <label className="formula-bar">Значение {columnLabel(c)}{r + 1}{cell.type === 'number' ? <NumberCellInput key={cell.id} value={cell.value} update={value => changeCell({ ...cell, value })} /> : cell.type === 'boolean' ? <select value={String(cell.value)} onChange={e => changeCell({ ...cell, value: e.target.value === 'true' })}><option value="true">ИСТИНА</option><option value="false">ЛОЖЬ</option></select> : <input aria-label="Значение выбранной ячейки" type={cell.type === 'date' ? 'date' : 'text'} value={String(cell.value)} maxLength={cell.type === 'formula' ? 300 : 1000} onChange={e => { if (cell.type === 'date') { if (e.target.value) changeCell({ ...cell, value: e.target.value }) } else changeCell({ ...cell, value: e.target.value }) }} />}</label></>}
    <div className="sheet-scroll"><table className="sheet-grid"><colgroup><col style={{ width: 45 }} />{sheet.columns.map(col => <col key={col.id} style={{ width: col.width * 8 }} />)}</colgroup><thead><tr><th /><>{sheet.columns.map((col, i) => <th key={col.id}>{columnLabel(i)}</th>)}</></tr></thead><tbody>{sheet.rows.map((row, ri) => <tr key={row.id} className={sheet.headerRow && ri === 0 ? 'sheet-header-row' : ''}><th>{ri + 1}</th>{row.cells.map((input, ci) => <td key={input.id} className={`${r === ri && c === ci && !preview ? 'active-cell' : ''} ${input.type === 'formula' && String(results[ri]![ci]).startsWith('#') ? 'cell-error' : ''}`}><button style={{ fontWeight: input.bold ? 700 : undefined }} title={input.type === 'formula' ? input.value : undefined} aria-label={`${columnLabel(ci)}${ri + 1}: ${display(input, ri, ci)}`} onClick={() => setAddress([ri, ci])}>{display(input, ri, ci) || '\u00a0'}</button></td>)}</tr>)}</tbody></table></div>
    {!preview && <><div className="office-toolbar"><button disabled={sheet.rows.length >= 100} onClick={() => change({ ...sheet, rows: [...sheet.rows, { id: crypto.randomUUID(), cells: sheet.columns.map(blankCell) }] })}>＋ Строка</button><button disabled={sheet.columns.length >= 12} onClick={() => change({ ...sheet, columns: [...sheet.columns, { id: crypto.randomUUID(), width: 24 }], rows: sheet.rows.map(row => ({ ...row, cells: [...row.cells, blankCell()] })) })}>＋ Колонка</button><button disabled={sheet.rows.length <= 1} onClick={() => { if (window.confirm('Удалить последнюю строку? Адреса формул не изменятся.')) change({ ...sheet, rows: sheet.rows.slice(0, -1) }) }}>− Последняя строка</button><button disabled={sheet.columns.length <= 1} onClick={() => { if (window.confirm('Удалить последнюю колонку? Адреса формул не изменятся.')) change({ ...sheet, columns: sheet.columns.slice(0, -1), rows: sheet.rows.map(row => ({ ...row, cells: row.cells.slice(0, -1) })) }) }}>− Последняя колонка</button></div><p className="muted small-note">Выберите ячейку и измените значение сверху. Формулы: + − * /, скобки, SUM, AVERAGE, MIN, MAX, COUNT и ссылки внутри листа, например =SUM(B2:B5). Для формул выберите тип «Формула»; текст со знаком = остаётся текстом.</p></>}
  </div>
}
